### ISSUE TITLE
[FEAT] postEditPage 수정

### ISSUE THREAD

**Issue by hyeonjinan096** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#110]
## Description
postEditPage의 전체적인 ui를 수정합니다. 
전체적인 코드 기능 추가 및 리팩토링을 합니다.

### ✅Todo
- [x] 스크롤바 컴포넌트 적용
- [x] input 스타일 변경
- [x] 마진 정리 
- [x] 삭제 아이콘 추가
