### ISSUE TITLE
[FIX] setting 레이아웃 수정, 라우팅 처리, 동적 토큰 처리

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#129]
### ✅Todo
- [x] 취소하기 버튼 중복제거
- [x] 라우팅 처리 진행
- [x] 동적 토큰 처리
