### ISSUE TITLE
[FIX] userPage, setting 뷰 로직 수정

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#133]
## Description
뷰 로직 수정 진행
코드 충돌이 예상되나 비즈니스 로직 수정이 없어 큰 문제 없을 것으로 예상됩니다.

### ✅Todo
- [x] userPage 너비 조정
- [x] userPage 게시글 없을 경우 텍스트 표현
- [x] setting input 위치 조정
- [x] setting svg 적용
- [x] setting 탈퇴하기 버튼 제거
