### ISSUE TITLE
[FIX] Index, 404 반응형 단위 변경

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#148]
## Description
Index, 404 페이지 크기 조절 작업 진행 예정

### ✅Todo
- [ ] Index 로고 단위 변경
- [ ] 404 Page 폰트 단위 변경
- [ ] Button 적정 크기 계산 → 차후 버튼 컴포넌트 크기 조절용

> Reference
