### ISSUE TITLE
[FIX] 로그아웃 api 요청 + PostComment 에러수정

### ISSUE THREAD

**Issue by YunSukHyun** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#151]
### ✅Todo
- [ ] PosComment 머지 후 생긴 에러 수정
- [ ] Logout시 api 요청하도록 수정
- [ ] Logout하면 /로 가지 않고 강제 새로고침으로 로그아웃만 되도록 수정

> Reference
