### ISSUE TITLE
[FEAT] UserStatusList 컴포넌트 구현

### ISSUE THREAD

**Issue by ienrum** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#16]
## Description
온 오프라인 유저 상태 정보를 나열하는 컴포넌트 구현

### ✅Todo
- [x] 오프라인 온라인 구분
- [x] online badge 와 결합
- [x] 내부에 Item 작성

> Reference
