### ISSUE TITLE
[FIX] Refactor 전 핫픽스

### ISSUE THREAD

**Issue by YunSukHyun** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#167]
## Description
- 리팩토링 하기 전에는 끝내야겠다고 생각되는거 수정
### ✅Todo
- [x] 마이페이지 이동 후 드랍다운 남아있는 현상
- [x] 이미지 삭제는 구현이 불가능 하다는 결론이 남
- [x] 버튼 disabled 제대로 동작 안되던 문제 수정 

> Reference
