### ISSUE TITLE
[FIX] User 폼 리뷰 반영

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#215]
## Description
폼 리뷰 반영 진행합니다.

### ✅Todo
- [ ] 최대한 한 줄에 게시글이 3개 나올 수 있도록 (페이지네이션 추가)
- [ ] 이후 좌우 스크롤로 전체 게시글 볼 수 있도록 수정 (스크롤 수정)
- [x] 한줄소개, 닉네임 길이 제한
