### ISSUE TITLE
[FEAT] Index 페이지 소개 추가

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#230]
## Description
이미지 캐러셀 추가 진행.
간략한 프로젝트 소개 추가

### ✅Todo
- [ ] 이미지 캐러셀 추가 (추가 패키지 예정)
- [ ] 페이지 레이아웃 변경
- [ ] 다크모드 예정 (캐러셀 내 이미지는 수정 불가능)
