### ISSUE TITLE
[FIX] 알림 ui, 데이터, 오류 수정

### ISSUE THREAD

**Issue by ienrum** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#234]
## Description
알림 관련 수정

### ✅Todo
- [x] 알림 UI 수정
- [x] 알림 데이터 수정
- [ ] 알림 오류 수정

> Reference
