### ISSUE TITLE
[FEAT] userPage UI제작

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#24]
## Description
User 정보를 보여주는 유저페이지 구현을 진행합니다.

### ✅Todo
- [ ] User InfoWrapper - avatar, text, button
- [ ] 잔디 컴포넌트 제작 - 표로 임시 컴포넌트 제작(추후 리팩토링 예정)
- [ ] User PostList - main 페이지 내 카드와 동일할 것 으로 예상되어 영역만 표시

> Reference
