### ISSUE TITLE
[FIX] 아이콘 svg 변경

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#252]
## Description
material-symbol, 일반 텍스트 모두 svg로 변경 예정

### ✅Todo
- [ ] 일반 아이콘은 svg로 변경
- [ ] 추가 기능사항 존재할 경우 tsx 파일로 사용.
- [ ] 다크모드 적용 확인
- [ ] 미사용 svg 제거
