### ISSUE TITLE
[Refector] Card 컴포넌트 레이아웃 수정

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#254]
## Description
Card 컴포넌트 내 레이아웃 관련 코드 수정

### ✅Todo
- [x] 투표 항목 색상 변경 확인
- [ ] 전체적인 카드 색 밝히기
- [ ] 로그인, Setting, 관리자페이지 카드색 변경
- [x] Title Text 말줄임 처리
