### ISSUE TITLE
[Refector] 슬라이스 폴더 리팩토링

### ISSUE THREAD

**Issue by ienrum** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#310]
## Description
리덕스 슬라이스 리팩토링

### ✅Todo
- [x] constants 폴더 공통으로 빼기
- [x] 필요한 selected 훅만 남기기
- [x] slice 코드 스타일 통일시키기

> Reference
