### ISSUE TITLE
[FIX] ProtectedRoute 로직 수정

### ISSUE THREAD

**Issue by YunSukHyun** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#319]
### ✅Todo
- [ ] ProtectedRoute 잘못된 동작이 있어서 수정
- [ ] sign, header에 useMemo, useCallback
- [ ] style tsx -> ts

> Reference
