### ISSUE TITLE
[FEAT] GlobalStyle 세팅

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#6]
## Description
styled-component 전체 적용 색상, 폰트 관련 정보 업로드 진행

### ✅Todo
- [x] reset.css 적용
- [x] theme.ts 개별 속성 값 대입
- [x] GlobalStyle 내 글로벌 스타일 작성

> Reference
