### ISSUE TITLE
[Refector] SettingModal 컴포넌트 속성 수정

### ISSUE THREAD

**Issue by hj9118** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#73]
## Description
Input, Avatar, Button 컴포넌트 속성 수정

### ✅Todo
- [ ] Input 속성 추가
- [ ] Avatar alt, defaultSrc 추가
- [ ] Button 아이콘 추가
