### ISSUE TITLE
[FEAT] Detail Page 실제데이터 렌더링

### ISSUE THREAD

**Issue by HoberMin** [prgrms-fe-devcourse/FEDC5_NodakNodak_Noah#81]
### ✅Todo
- [ ] store에 저장되어있는 데이터를 Component에 전달
- [ ] comment데이터 주입
- [ ] 실제 데이터가 렌더링 될 수 있도록 변환
- [ ] 뷰로직 수정 - 투표항목, 컴포넌트 별 간격 등등
